from core.config.color import Color

class Config:
    MAPS_FOLDER = "maps"
    GRID_SIZE = 40
    BUTTON_SIZE = 50
    STATION_RECT_WIDTH = 6
    STATION_RECT_HEIGHT = 1
    FPS = 20
    
    
    MIN_TRACK_SPEED = 10
    MAX_TRACK_SPEED = 200
    TRACK_SPEED_INCREMENT = 10
    SHORT_SECTION_LENGTH = 50
    LONG_SECTION_LENGTH = 250
    
    TRAIN_CAR_LENGTH = 25
    TRAIN_CAR_GAP = 5
    MAX_TRAIN_CAR_COUNT = 16
    MAX_PLATFORM_EDGE_COUNT = 12
    MIN_TRAIN_STOP_TIME = 30  #seconds
    TRAIN_SAFETY_BUFFER = 10  #meters
    
    
    TRAIN_SHUTDOWN_COLOR = Color.DARKGREY
    TRAIN_LIVE_COLOR = Color.GREY