from core.config.color import Color

class Config:
    MAPS_FOLDER = "maps"
    GRID_SIZE = 40
    BUTTON_SIZE = 50
    STATION_RECT_WIDTH = 6
    STATION_RECT_HEIGHT = 1
    FPS = 30

    SHORT_SEGMENT_LENGTH = 50
    LONG_SEGMENT_LENGTH = 250
    
    TRAIN_CAR_LENGTH = 25
    TRAIN_CAR_GAP = 5
    MAX_TRAIN_CAR_COUNT = 16
    MAX_PLATFORM_EDGE_COUNT = 12
    MIN_TRAIN_STOP_TIME = 30  #seconds
    
    
    TRAIN_SHUTDOWN_COLOR = Color.DARKGREY
    TRAIN_LIVE_COLOR = Color.GREY